"""text_generation_columns

Revision ID: 16715379e79b
Revises: 9f3c1a7d5e2b
Create Date: 2026-09-07 01:13:54.313483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16715379e79b'
down_revision: Union[str, Sequence[str], None] = '9f3c1a7d5e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new values to postgres enums
    op.execute(sa.text("ALTER TYPE source_type ADD VALUE IF NOT EXISTS 'text'"))
    op.execute(sa.text("ALTER TYPE video_project_status ADD VALUE IF NOT EXISTS 'generating'"))
    op.add_column('video_projects', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('video_projects', sa.Column('shorts_count', sa.Integer(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_projects', 'shorts_count')
    op.drop_column('video_projects', 'description')
    # ### end Alembic commands ###
