"""initial

Creates the six core tables for VideoToShorts: users, refresh_tokens,
video_projects, transcript_segments, clips, and broll_assets.

Hand-written (not autogenerated): no reachable local Postgres instance was
available in this environment to run `alembic revision --autogenerate`, so
this migration was authored by hand to mirror the SQLAlchemy models exactly
(see backend/app/models/). It should be verified/regenerated with
`alembic check` or a fresh `--autogenerate` diff against a live DB before
relying on it in production.

Revision ID: be97e4a7ba79
Revises:
Create Date: 2026-08-29 13:47:33.025309

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be97e4a7ba79"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("is_verified", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("is_admin", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=False)

    source_type_enum = sa.Enum("upload", "url", name="source_type")
    video_project_status_enum = sa.Enum(
        "pending",
        "downloading",
        "transcribing",
        "analyzing",
        "ready",
        "failed",
        name="video_project_status",
    )
    op.create_table(
        "video_projects",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("source_type", source_type_enum, nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("source_file_path", sa.String(length=1024), nullable=True),
        sa.Column(
            "status",
            video_project_status_enum,
            nullable=False,
            server_default="pending",
        ),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_video_projects_id"), "video_projects", ["id"], unique=False)
    op.create_index(op.f("ix_video_projects_user_id"), "video_projects", ["user_id"], unique=False)

    op.create_table(
        "transcript_segments",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("video_project_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_highlight", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("highlight_score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["video_project_id"], ["video_projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transcript_segments_id"), "transcript_segments", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_transcript_segments_video_project_id"),
        "transcript_segments",
        ["video_project_id"],
        unique=False,
    )

    clip_status_enum = sa.Enum("draft", "rendering", "ready", "failed", name="clip_status")
    op.create_table(
        "clips",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("video_project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("status", clip_status_enum, nullable=False, server_default="draft"),
        sa.Column("caption_text", sa.Text(), nullable=True),
        sa.Column("video_file_path", sa.String(length=1024), nullable=True),
        sa.Column("thumbnail_path", sa.String(length=1024), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["video_project_id"], ["video_projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clips_id"), "clips", ["id"], unique=False)
    op.create_index(op.f("ix_clips_video_project_id"), "clips", ["video_project_id"], unique=False)
    op.create_index(op.f("ix_clips_user_id"), "clips", ["user_id"], unique=False)

    broll_source_enum = sa.Enum("pexels", "pixabay", name="broll_source")
    op.create_table(
        "broll_assets",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("clip_id", sa.Integer(), nullable=False),
        sa.Column("source", broll_source_enum, nullable=False),
        sa.Column("source_asset_id", sa.String(length=255), nullable=False),
        sa.Column("asset_url", sa.String(length=2048), nullable=False),
        sa.Column("keyword", sa.String(length=255), nullable=False),
        sa.Column("position_start", sa.Float(), nullable=False),
        sa.Column("position_end", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_broll_assets_id"), "broll_assets", ["id"], unique=False)
    op.create_index(op.f("ix_broll_assets_clip_id"), "broll_assets", ["clip_id"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_broll_assets_clip_id"), table_name="broll_assets")
    op.drop_index(op.f("ix_broll_assets_id"), table_name="broll_assets")
    op.drop_table("broll_assets")

    op.drop_index(op.f("ix_clips_user_id"), table_name="clips")
    op.drop_index(op.f("ix_clips_video_project_id"), table_name="clips")
    op.drop_index(op.f("ix_clips_id"), table_name="clips")
    op.drop_table("clips")

    op.drop_index(op.f("ix_transcript_segments_video_project_id"), table_name="transcript_segments")
    op.drop_index(op.f("ix_transcript_segments_id"), table_name="transcript_segments")
    op.drop_table("transcript_segments")

    op.drop_index(op.f("ix_video_projects_user_id"), table_name="video_projects")
    op.drop_index(op.f("ix_video_projects_id"), table_name="video_projects")
    op.drop_table("video_projects")

    op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")

    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")

    # Enum types created implicitly by create_table above must be dropped
    # explicitly on downgrade (PostgreSQL only).
    sa.Enum(name="clip_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="video_project_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="source_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="broll_source").drop(op.get_bind(), checkfirst=True)
